import logging


DEFAULT_NUM_PARTITIONS = 1

FOGV_CMD_REQUEST_DEPLOY = 'REQUEST_DEPLOY'

FOGV_STATUS_CLOUD_DEPLOYED = 'DEPLOYED_IN_CLOUD'
FOGV_STATUS_RUNNING = 'RUNNING'
FOGV_STATUS_RUN_IN_CLOUD = 'RUN_IN_CLOUD'
FOGV_STATUS_RUN_IN_LOCAL = 'RUN_IN_LOCAL'
FOGV_STATUS_SHUTDOWN = 'SHUTDOWN'

FOGV_STDOUT = logging.INFO + 2
FOGV_CSV = logging.INFO + 4
FOGV_FILE = logging.INFO + 8
