DEFAULT_NUM_PARTITIONS = 1

FOGV_STATUS_RUNNING = "RUNNING"
FOGV_STATUS_SHUTDOWN = "SHUTDOWN"
FOGV_STATUS_RUN_IN_CLOUD = "RUN_IN_CLOUD"
FOGV_STATUS_RUN_IN_LOCAL = "RUN_IN_LOCAL"
FOGV_STATUS_CLOUD_DEPLOYED = "DEPLOYED_IN_CLOUD"

FOGV_CMD_REQUEST_DEPLOY = "REQUEST_DEPLOY"

DEFAULT_FMT = "[%(asctime)s][%(levelname)s][%(name)s] %(message)s"

# Numbers are arbitrary, but must be unique.
FOGV_STDOUT = 24
FOGV_TXT = 25
FOGV_CSV = 26
