apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ topic_name }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: {{ partitions }}
  replicas: {{ replication_factor }}