topics: [ 'test-topic' ]
partitioning_params:
  algorithm: [ 'BroMin', 'BroMax' ]
  T: 1.e+8
  L: 0.2
  U: 2
  Tp: 8.14e+6
  Tc: 1.0143137e+7
  Hmax: 16384
  lr: 5.e-3
  u: 2.662e-1
  c: 1
  r: 3
  B: 10
